{
    "name": "Liya Demo Form",
    "version": "18.0.0.0",
    "category": "Sale",
    "depends": ['project', 'sale', 'sale_management', 'liya_sale_flow', 'crm', 'sale_project','calendar','mail'],
    "author": "Broadmax",
    'summary': 'Liya Demo Form',
    "description": """
        Liya Demo Form
	""",
    "website": "https://broadmax.com.tr",
    "data": [
        "views/demo_form.xml",
        "views/project_template_view.xml",
        "views/sale_order_view_inherit.xml",
        "views/sale_order_template_view.xml",
        "views/crm_lead_view_inherit.xml",
        "views/project_task_view_inherit.xml",
        "views/many2many_list_views.xml",
        "data/project_task_menu_views.xml",
        "data/check_project_stage_cron.xml",
        "data/demo_compute_cron.xml",
        "data/project_menu_restrict.xml",
        "wizards/sale_order_project_wizard_view.xml",
        "wizards/update_project_wizard.xml",
        "wizards/extra_protocol_wizard_view.xml",
        "reports/report_demo_form.xml",
        "security/ir.model.access.csv",
        "views/partner_data_views.xml",
    ],
    "auto_install": False,
    "installable": True,
    "license": "AGPL-3",
}
