{
    "name": "Liya Sale Flow",
    "version": "18.0.0.0",
    "category": "Sale",
    "depends": [ 'sale',  'crm','base','sale_management','project','mail'],
    "author": "Broadmax",
    'summary': 'Liya Sale Flow',
    "description": """
        Liya Sale Flow
	""",
    "website": "https://broadmax.com.tr",
    "data": [
        "views/crm_lead.xml",
        "views/sale_order_template_view.xml",
        "views/sale_order_view_inherit.xml",
        "views/crm_lead_kanban_hide_revenues.xml",
        "views/product_template_view_inherit.xml",
        "views/calendar_event_inherit_search_custom.xml",
        "views/calendar_event_form_inherit.xml",
        "views/crm_team_inherit.xml",
        "views/res_partner_inherit_requireds.xml",
        "views/mail_activity_type.xml",
        "views/crm_lead_opportunity_menu.xml",
        "security/ir.model.access.csv",
        "reports/report_saleorder_document_inherit.xml",
        "reports/external_layout_light_view_inherit.xml",
        "reports/report_saleorder_banquet.xml",
        #"reports/report_sale_order_raw_inherit.xml",
        "data/ir_sequence.xml",
        "data/calendar_alarm_data.xml",
        "data/menu_restrict.xml",

    ],
    "auto_install": False,
    "installable": True,
    "license": "AGPL-3",
}
