from . import crm_lead
from . import wedding_type
from . import sale_order_template
from . import sale_order
from . import calendar_alarm
from . import activity_type
from . import wedding_place
from . import product_template
from . import event_event
from . import sales_teams